[package]
name = "wifyyy"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"]}
serde = { version = "1.0", features = ["derive"]}
tokio = { version= "1", features = ["full"]}
